### ISSUE TITLE
must the name of fasta files end with ".fa" or ".fasta"?

### ISSUE THREAD

**Issue by shinout** [nariai/tigar2#1]
java -jar Tigar.jar fasta_name sample.sam sample.out

cannot be executed.
After renaming fasta_name as fasta_name.fa worked.

**Comment by nariai** [comment]
Interesting. This might be a Picard library issue.. Sorry for (very) late reply!

**Comment by nariai** [comment]
It looks like better to name ".fa" or ".fasta".
Let me close this.
